# -*- coding: utf-8 -*-
"""test1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xK8NSsUcz4QUkU4N67vML7lNvj2n6Ja0
"""

# import pandas as pd
# import numpy as np
# from scipy.interpolate import griddata
# import plotly.graph_objects as go
# import math

# # --- 1. Load XYZ file ---
# df = pd.read_excel("/content/drive/MyDrive/LandSense/HGT_20_Segments/segment_2.xlsx")

# lon = df["x"].values
# lat = df["y"].values
# z   = df["z"].values

# # --- 2. Convert lon/lat -> meters ---
# lat0 = lat.mean()

# m_per_deg_lat = 111320
# m_per_deg_lon = 111320 * math.cos(math.radians(lat0))

# x = (lon - lon.min()) * m_per_deg_lon
# y = (lat - lat.min()) * m_per_deg_lat

# # --- 3. Compute ranges ---
# x_range = x.max() - x.min()
# y_range = y.max() - y.min()
# z_range = z.max() - z.min()

# print("x range (m):", x_range)
# print("y range (m):", y_range)
# print("z range (m):", z_range)

# # --- 4. Scale factors to prevent flat terrain ---
# scale_x = z_range / x_range if x_range != 0 else 1
# scale_y = z_range / y_range if y_range != 0 else 1

# print("scale_x:", scale_x)
# print("scale_y:", scale_y)

# # --- 5. Create auto-resolution grid ---
# resolution_per_km = 30
# Nx = int(np.clip(int((x_range / 1000) * resolution_per_km), 200, 3000))
# Ny = int(np.clip(int((y_range / 1000) * resolution_per_km), 200, 3000))

# print(f"Grid resolution: Nx={Nx}, Ny={Ny}")

# x_grid_vals = np.linspace(x.min(), x.max(), Nx)
# y_grid_vals = np.linspace(y.min(), y.max(), Ny)
# x_grid, y_grid = np.meshgrid(x_grid_vals, y_grid_vals)

# points = np.vstack((x, y)).T

# # --- 6. Interpolate Z ---
# z_grid = griddata(points, z, (x_grid, y_grid), method='linear')
# z_grid = np.nan_to_num(z_grid, nan=np.nanmean(z_grid))

# # --- 7. Apply scaling for visualization ONLY ---
# x_vis = x_grid * scale_x
# y_vis = y_grid * scale_y

# # --- 8. 3D Plot ---
# fig = go.Figure(data=[
#     go.Surface(
#         x=x_vis,
#         y=y_vis,
#         z=z_grid,
#         colorscale="Viridis",
#         showscale=True
#     )
# ])

# fig.update_layout(
#     title='3D Terrain with X-Y Scaling (No Flatness)',
#     scene=dict(
#         xaxis_title='Scaled X (m)',
#         yaxis_title='Scaled Y (m)',
#         zaxis_title='Elevation (m)',
#         aspectmode='cube'
#     ),
#     height=900,
#     margin=dict(l=0, r=0, b=0, t=40)
# )

# fig.show()

import pandas as pd
import numpy as np
from scipy.interpolate import griddata
import plotly.graph_objects as go
import math

# --- 1. Load XYZ file ---
df = pd.read_excel("/content/drive/MyDrive/LandSense/HGT_20_Segments/segment_1.xlsx")

lon = df["x"].values        # longitude (deg)
lat = df["y"].values        # latitude (deg)
z   = df["z"].values       # elevation (meters)

print(df.head(20))

# --- 2. Convert lon/lat -> meters ---
lat0 = lat.mean()

m_per_deg_lat = 111320
m_per_deg_lon = 111320 * math.cos(math.radians(lat0))

x = (lon - lon.min()) * m_per_deg_lon
y = (lat - lat.min()) * m_per_deg_lat

# --- 3. Compute real scale ranges ---
x_min, x_max = x.min(), x.max()
y_min, y_max = y.min(), y.max()

x_range = x_max - x_min
y_range = y_max - y_min

# --- 4. Auto grid resolution ---
resolution_per_km = 30  # points per km

Nx = int((x_range / 1000) * resolution_per_km)
Ny = int((y_range / 1000) * resolution_per_km)

Nx = int(np.clip(Nx, 200, 3000))
Ny = int(np.clip(Ny, 200, 3000))

print(f"Auto grid resolution: Nx={Nx}, Ny={Ny}")

# --- 5. Create grid ---
x_grid = np.linspace(x_min, x_max, Nx)
y_grid = np.linspace(y_min, y_max, Ny)
x_grid, y_grid = np.meshgrid(x_grid, y_grid)

points = np.vstack((x, y)).T

# --- 6. Interpolate Z ---
z_grid = griddata(points, z, (x_grid, y_grid), method='linear')
z_grid = np.nan_to_num(z_grid, nan=np.nanmean(z_grid))

# # --- 7. 3D Plot (XYZ only) ---
# fig = go.Figure(data=[
#     go.Surface(
#         x=x_grid,
#         y=y_grid,
#         z=z_grid,
#         colorscale="Viridis",
#         showscale=False
#     )
# ])

# fig.update_layout(
#     title='3D Terrain (lon/lat converted to meters)',
#     scene=dict(
#         xaxis_title='X (m)',
#         yaxis_title='Y (m)',
#         zaxis_title='Elevation (m)',
#         aspectratio=dict(x=1, y=0.1, z=0.1)
#     ),
#     height=900,
#     margin=dict(l=0, r=0, b=0, t=40)
# )

# fig.show()

df

"""This part is to test please use smap for actual soil moisture base value"""

import requests

# 🔹 Enter your coordinates here
latitude = 15.0
longitude = 74.00

# Open-Meteo Soil Moisture API URL
url = (
    "https://api.open-meteo.com/v1/forecast"
    f"?latitude={latitude}&longitude={longitude}"
    "&hourly=soil_moisture_0_1cm,soil_moisture_1_3cm,soil_moisture_3_9cm"
)

response = requests.get(url)
data = response.json()

# ✅ Extract latest soil moisture values
latest_index = -1

moisture_0_1 = data["hourly"]["soil_moisture_0_1cm"][latest_index]
moisture_1_3 = data["hourly"]["soil_moisture_1_3cm"][latest_index]
moisture_3_9 = data["hourly"]["soil_moisture_3_9cm"][latest_index]
time = data["hourly"]["time"][latest_index]

print("📍 Location:", latitude, longitude)
print("🕒 Time:", time)
print("🌱 Soil Moisture 0–1 cm:", moisture_0_1)
print("🌱 Soil Moisture 1–3 cm:", moisture_1_3)
print("🌱 Soil Moisture 3–9 cm:", moisture_3_9)

# Full corrected optimized pipeline (GPU-safe D8)
# Run in one cell. Requires: numpy, pandas, scipy, scipy.ndimage. CuPy optional.

import time
t_all = time.time()

import numpy as np
import pandas as pd
from scipy.interpolate import griddata
from scipy.ndimage import gaussian_filter
import warnings
warnings.filterwarnings("ignore")

# ---------------- PARAMETERS ----------------
IN_POINTS_CSV = "/content/drive/MyDrive/LandSense/HGT_20_Segments/segment_1.xlsx"   # must contain x,y,z,dz
NUM_GRID = 500         # grid resolution (500 => 250k cells). reduce to 300 for speed.
SMOOTH_SIGMA = 2       # gaussian smoothing sigma
BASE_MOISTURE = 0.035
ALPHA_TWI = 0.8
LANDSLIDE_BOOST_MIN = 0.05
LANDSLIDE_BOOST_MAX = 0.15
TWI_EPS = 1e-12

# ---------------- TRY GPU (CuPy) ----------------
use_gpu = False
xp = np
cp = None
try:
    import cupy as cp
    from cupyx.scipy import ndimage as cnd
    use_gpu = True
    xp = cp
    print("CuPy available — GPU will be used.")
except Exception:
    print("CuPy not available — using CPU (NumPy).")

# ---------------- LOAD POINTS ----------------
t0 = time.time()
df = pd.read_excel(IN_POINTS_CSV) # Changed from pd.read_csv to pd.read_excel
print(f"Loaded {len(df)} points ({time.time()-t0:.2f}s)")

lon = df["x"].values
lat = df["y"].values
z   = df["z"].values
dz  = np.zeros_like(z)

lat0 = lat.mean()

m_per_deg_lat = 111320.0
m_per_deg_lon = 111320.0 * np.cos(np.radians(lat0))

x = (lon - lon.min()) * m_per_deg_lon
y = (lat - lat.min()) * m_per_deg_lat

df["x"] = x
df["y"] = y

points = np.vstack((x, y)).T

# ---------------- BUILD GRID ----------------
t0 = time.time()
x_min, x_max = x.min(), x.max()
y_min, y_max = y.min(), y.max()

X_lin = np.linspace(x_min, x_max, NUM_GRID)
Y_lin = np.linspace(y_min, y_max, NUM_GRID)
Xg, Yg = np.meshgrid(X_lin, Y_lin)

# linear interp then nearest fill for NaNs
Zg = griddata(points, z, (Xg, Yg), method="linear")
nan_mask = np.isnan(Zg)
if nan_mask.any():
    Z_near = griddata(points, z, (Xg, Yg), method="nearest")
    Zg[nan_mask] = Z_near[nan_mask]

dx = float(np.mean(np.diff(Xg[0, :])))
dy = float(np.mean(np.diff(Yg[:, 0])))
print(f"Grid {NUM_GRID}x{NUM_GRID} created (dx={dx:.4g}, dy={dy:.4g}) in {time.time()-t0:.2f}s")

# ---------------- TRANSFER TO GPU IF AVAILABLE ----------------
if use_gpu:
    t0 = time.time()
    Zg_gpu = xp.array(Zg)   # cupy array
    print(f"Transferred DEM to GPU in {time.time()-t0:.2f}s")
else:
    Zg_gpu = Zg  # numpy array (alias)

# ---------------- SMOOTH DEM ----------------
t0 = time.time()
if use_gpu:
    Zs_gpu = cnd.gaussian_filter(Zg_gpu, sigma=SMOOTH_SIGMA, mode='reflect')
else:
    Zs_gpu = gaussian_filter(Zg_gpu, sigma=SMOOTH_SIGMA, mode='reflect')
print(f"DEM smoothed (sigma={SMOOTH_SIGMA}) in {time.time()-t0:.2f}s")

# ---------------- SLOPE & ASPECT ----------------
t0 = time.time()
if use_gpu:
    dzdy_gpu, dzdx_gpu = xp.gradient(Zs_gpu, dy, dx)
    slope_mag_gpu = xp.sqrt(dzdx_gpu*2 + dzdy_gpu*2)
    slope_rad_gpu = xp.arctan(slope_mag_gpu)
    slope_deg_gpu = xp.degrees(slope_rad_gpu)
    aspect_gpu = xp.degrees(xp.arctan2(-dzdy_gpu, -dzdx_gpu))
    aspect_gpu = (aspect_gpu + 360) % 360
else:
    dzdy_gpu, dzdx_gpu = np.gradient(Zs_gpu, dy, dx)
    slope_mag_gpu = np.sqrt(dzdx_gpu*2 + dzdy_gpu*2)
    slope_rad_gpu = np.arctan(slope_mag_gpu)
    slope_deg_gpu = np.degrees(slope_rad_gpu)
    aspect_gpu = np.degrees(np.arctan2(-dzdy_gpu, -dzdx_gpu))
    aspect_gpu = (aspect_gpu + 360) % 360
print(f"Slope & aspect computed in {time.time()-t0:.2f}s")

# ---------------- CURVATURES ----------------
t0 = time.time()
if use_gpu:
    d2z_dx2_gpu = xp.gradient(dzdx_gpu, dx, axis=1)
    d2z_dy2_gpu = xp.gradient(dzdy_gpu, dy, axis=0)
    d2z_dxdy_gpu = xp.gradient(dzdx_gpu, dy, axis=0)
    profile_curv_gpu = (
        (dzdx_gpu*2 * d2z_dx2_gpu + 2 * dzdx_gpu * dzdy_gpu * d2z_dxdy_gpu + dzdy_gpu*2 * d2z_dy2_gpu)
        / ((dzdx_gpu*2 + dzdy_gpu*2 + 1)*1.5)
    )
    plan_curv_gpu = (
        (dzdx_gpu*2 * d2z_dy2_gpu - 2 * dzdx_gpu * dzdy_gpu * d2z_dxdy_gpu + dzdy_gpu*2 * d2z_dx2_gpu)
        / ((dzdx_gpu*2 + dzdy_gpu*2)*1.5 + 1e-12)
    )
else:
    d2z_dx2_gpu = np.gradient(dzdx_gpu, dx, axis=1)
    d2z_dy2_gpu = np.gradient(dzdy_gpu, dy, axis=0)
    d2z_dxdy_gpu = np.gradient(dzdx_gpu, dy, axis=0)
    profile_curv_gpu = (
        (dzdx_gpu*2 * d2z_dx2_gpu + 2 * dzdx_gpu * dzdy_gpu * d2z_dxdy_gpu + dzdy_gpu*2 * d2z_dy2_gpu)
        / ((dzdx_gpu*2 + dzdy_gpu*2 + 1)*1.5)
    )
    plan_curv_gpu = (
        (dzdx_gpu*2 * d2z_dy2_gpu - 2 * dzdx_gpu * dzdy_gpu * d2z_dxdy_gpu + dzdy_gpu*2 * d2z_dx2_gpu)
        / ((dzdx_gpu*2 + dzdy_gpu*2)*1.5 + 1e-12)
    )
print(f"Curvatures computed in {time.time()-t0:.2f}s")

# ---------------- TRI & ROUGHNESS (neighbor shifts) ----------------
t0 = time.time()
# neighbors: 8 shifts (N, NE, E, SE, S, SW, W, NW)
shifts = [(-1,0), (-1,1), (0,1), (1,1), (1,0), (1,-1), (0,-1), (-1,-1)]
if use_gpu:
    neighbors = [xp.roll(xp.roll(Zg_gpu, dy_, axis=0), dx_, axis=1) for (dy_, dx_) in shifts]
    tri_gpu = xp.zeros_like(Zg_gpu)
    for n in neighbors:
        tri_gpu += xp.abs(n - Zg_gpu)
    stack = xp.stack(neighbors + [Zg_gpu], axis=0)
    rough_gpu = stack.max(axis=0) - stack.min(axis=0)
else:
    neighbors = [np.roll(np.roll(Zg, dy_, axis=0), dx_, axis=1) for (dy_, dx_) in shifts]
    tri_gpu = np.zeros_like(Zg)
    for n in neighbors:
        tri_gpu += np.abs(n - Zg)
    stack = np.stack(neighbors + [Zg], axis=0)
    rough_gpu = stack.max(axis=0) - stack.min(axis=0)
print(f"TRI & roughness computed in {time.time()-t0:.2f}s")

# ---------------- GPU-SAFE D8 FLOW ACCUMULATION ----------------
t0 = time.time()
def d8_flow_accum_gpu(Z2d, xpmod):
    """
    GPU-safe D8 flow accumulation. Works with numpy or cupy arrays.
    Returns flow accumulation array same dtype as input.
    """
    rows, cols = Z2d.shape
    # neighbor offsets (clockwise)
    d_row = xpmod.array([-1, -1, 0, 1, 1, 1, 0, -1], dtype=xpmod.int32)
    d_col = xpmod.array([0, 1, 1, 1, 0, -1, -1, -1], dtype=xpmod.int32)

    # Preallocate flow direction and best drop
    fdir = -xpmod.ones((rows, cols), dtype=xpmod.int8)
    best_drop = -xpmod.ones((rows, cols), dtype=xpmod.float64) * xpmod.inf

    # coordinate grids
    R = xpmod.arange(rows)[:, None]
    C = xpmod.arange(cols)[None, :]

    # determine steepest downhill neighbor for each cell
    for k in range(8):
        nr = R + d_row[k]
        nc = C + d_col[k]
        valid = (nr >= 0) & (nr < rows) & (nc >= 0) & (nc < cols)

        # neighbor elevation (for invalid neighbor positions we set neighbor elev equal to cell elev so drop=0)
        if xpmod is np:
            neigh = np.where(valid, Z2d[nr, nc], Z2d)
        else:
            neigh = xpmod.where(valid, Z2d[nr, nc], Z2d)

        drop = Z2d - neigh  # positive if neighbor lower
        better = (drop > 0) & (drop > best_drop)

        # update best_drop and fdir where better
        best_drop = xpmod.where(better, drop, best_drop)
        fdir = xpmod.where(better, k, fdir)

    # flow accumulation: start with 1 per cell
    FA = xpmod.ones((rows, cols), dtype=xpmod.float64)

    # topological order: cells sorted from high to low elevation
    # we need flattened ordering but operate with flat indices converted to 2D
    flat_order = xpmod.argsort(Z2d.ravel())[::-1]
    # convert to r,c arrays for iteration
    if xpmod is np:
        rr = (flat_order // cols)
        cc = (flat_order % cols)
        for r, c in zip(rr, cc):
            k = int(fdir[r, c])
            if k >= 0:
                r2 = r + int(d_row[k])
                c2 = c + int(d_col[k])
                if 0 <= r2 < rows and 0 <= c2 < cols:
                    FA[r2, c2] += FA[r, c]
    else:
        # cupy: convert order to host lists to iterate without fancy indexing complications
        flat_host = xpmod.asnumpy(flat_order)   # transfer sorted indices to CPU
        for flat_idx in flat_host:
            r = int(flat_idx // cols)
            c = int(flat_idx % cols)
            k = int(xpmod.asnumpy(fdir[r, c]))
            if k >= 0:
                r2 = r + int(xpmod.asnumpy(d_row[k]))
                c2 = c + int(xpmod.asnumpy(d_col[k]))
                if 0 <= r2 < rows and 0 <= c2 < cols:
                    # update on GPU directly
                    FA[r2, c2] += FA[r, c]

    return FA

# call the D8 function using correct module
if use_gpu:
    flow_acc_gpu = d8_flow_accum_gpu(Zs_gpu, cp)
else:
    flow_acc_gpu = d8_flow_accum_gpu(Zs_gpu, np)

flow_acc_gpu = flow_acc_gpu.astype(np.float64)
flow_acc_gpu[flow_acc_gpu < 1] = 1.0
print(f"D8 flow accumulation computed in {time.time()-t0:.2f}s")

# ---------------- TWI & NORMALIZE ----------------
t0 = time.time()
cell_area = dx * dy
if use_gpu:
    TWI_gpu = xp.log((flow_acc_gpu * cell_area) / (xp.tan(slope_rad_gpu) + TWI_EPS))
    TWI_gpu = xp.nan_to_num(TWI_gpu, nan=xp.nanmedian(TWI_gpu), posinf=xp.nanmax(TWI_gpu), neginf=xp.nanmin(TWI_gpu))
    TWI_norm_gpu = (TWI_gpu - TWI_gpu.min()) / (TWI_gpu.max() - TWI_gpu.min() + 1e-12)
else:
    TWI_gpu = np.log((flow_acc_gpu * cell_area) / (np.tan(slope_rad_gpu) + TWI_EPS))
    TWI_gpu = np.nan_to_num(TWI_gpu, nan=np.nanmedian(TWI_gpu), posinf=np.nanmax(TWI_gpu), neginf=np.nanmin(TWI_gpu))
    TWI_norm_gpu = (TWI_gpu - np.nanmin(TWI_gpu)) / (np.nanmax(TWI_gpu) - np.nanmin(TWI_gpu) + 1e-12)
print(f"TWI computed & normalized in {time.time()-t0:.2f}s")

# ---------------- MAP SOIL MOISTURE ON GRID ----------------
t0 = time.time()
if use_gpu:
    soil_grid_gpu = BASE_MOISTURE + ALPHA_TWI * TWI_norm_gpu
    soil_grid = xp.asnumpy(soil_grid_gpu)
else:
    soil_grid = BASE_MOISTURE + ALPHA_TWI * TWI_norm_gpu
print(f"Soil moisture mapped on grid in {time.time()-t0:.2f}s")

# ---------------- INTERPOLATE dz & soil BACK TO POINTS ----------------
t0 = time.time()
# interpolate dz to grid (linear then nearest fill)
DZg = griddata(points, dz, (Xg, Yg), method="linear")
nan_mask_dz = np.isnan(DZg)
if nan_mask_dz.any():
    DZg_near = griddata(points, dz, (Xg, Yg), method="nearest")
    DZg[nan_mask_dz] = DZg_near[nan_mask_dz]

soil_initial = griddata((Xg.flatten(), Yg.flatten()), soil_grid.flatten(), (x, y), method='linear')
soil_initial = np.nan_to_num(soil_initial, nan=np.nanmean(soil_initial))
print(f"Interpolated dz & soil back to points in {time.time()-t0:.2f}s")

# ---------------- LANDSLIDE BOOST ----------------
t0 = time.time()
mask_ls = dz < 0
randp = np.random.rand(len(df))
boost_mask = mask_ls & (randp < 0.75)
boost_amounts = np.zeros(len(df))
boost_amounts[boost_mask] = np.random.uniform(LANDSLIDE_BOOST_MIN, LANDSLIDE_BOOST_MAX, boost_mask.sum())

soil_final = soil_initial + boost_amounts
soil_final = np.clip(soil_final, 0.0, 1.0)
df["soil_moisture"] = soil_final
print(f"Landslide boost applied in {time.time()-t0:.2f}s (boosted {boost_mask.sum()} points)")

# ---------------- SAVE OUTPUTS ----------------
t0 = time.time()
def to_cpu(arr):
    if use_gpu:
        return xp.asnumpy(arr)
    return arr

out_grid_df = pd.DataFrame({
    "x": Xg.flatten(),
    "y": Yg.flatten(),
    "z": to_cpu(Zg).flatten(),
    "dz": DZg.flatten(),
    "slope_deg": to_cpu(slope_deg_gpu if use_gpu else slope_deg_gpu).flatten(),
    "aspect_deg": to_cpu(aspect_gpu if use_gpu else aspect_gpu).flatten(),
    "profile_curvature": to_cpu(profile_curv_gpu if use_gpu else profile_curv_gpu).flatten(),
    "plan_curvature": to_cpu(plan_curv_gpu if use_gpu else plan_curv_gpu).flatten(),
    "tri": to_cpu(tri_gpu if use_gpu else tri_gpu).flatten(),
    "roughness": to_cpu(rough_gpu if use_gpu else rough_gpu).flatten(),
    "twi": to_cpu(TWI_gpu if use_gpu else TWI_gpu).flatten(),
    "twi_norm": to_cpu(TWI_norm_gpu if use_gpu else TWI_norm_gpu).flatten(),
    "soil_moisture": soil_grid.flatten()
})

out_grid_csv = "/content/terrain_gpu_all_features_fixed.csv"
out_points_csv = "/content/xyz_with_soilmoisture_fixed.csv"
out_grid_df.to_csv(out_grid_csv, index=False)
df.to_csv(out_points_csv, index=False)
print(f"Saved grid -> {out_grid_csv}")
print(f"Saved points -> {out_points_csv}")
print(f"Saved outputs in {time.time()-t0:.2f}s")

print(f"\nTOTAL ELAPSED TIME: {time.time()-t_all:.2f}s")

import pandas as pd
import numpy as np
from scipy.interpolate import griddata
import plotly.graph_objects as go

# --- 1. Load the after_with_dz file ---
df = pd.read_csv("/content/xyz_with_soilmoisture_fixed.csv")

x = df["x"].values
y = df["y"].values
z = df["z"].values       # Elevation after landslide
dz = df["soil_moisture"].values     # Elevation change

# --- 2. Create Regular Grid ---
x_min, x_max = x.min(), x.max()
y_min, y_max = y.min(), y.max()

num_grid_points = 200   # Increase for smoother surface

x_grid = np.linspace(x_min, x_max, num_grid_points)
y_grid = np.linspace(y_min, y_max, num_grid_points)
x_grid, y_grid = np.meshgrid(x_grid, y_grid)

# Interpolation Points
points = np.vstack((x, y)).T

# --- 3. Interpolate Z and dz onto the grid ---
z_grid = griddata(points, z, (x_grid, y_grid), method='linear')
dz_grid = griddata(points, dz, (x_grid, y_grid), method='linear')

# Replace NaNs at edges with mean values
z_grid = np.nan_to_num(z_grid, nan=np.nanmean(z_grid))
dz_grid = np.nan_to_num(dz_grid, nan=0)

# --- 4. Create 3D Surface Plot Colored by dz ---
# fig = go.Figure(data=[go.Surface(
#     x=x_grid,
#     y=y_grid,
#     z=z_grid,
#     surfacecolor=dz_grid,   # <-- Color based on dz
#     colorbar=dict(title="dz"),
#     colorscale="RdBu"       # Blue = erosion, Red = deposition
# )])

# fig.update_layout(
#     title='3D Landslide Surface Colored',
#     scene=dict(
#         xaxis_title='X',
#         yaxis_title='Y',
#         zaxis_title='Elevation (Z)',
#         aspectratio=dict(x=10, y=1, z=1)
#     ),
#     margin=dict(l=0, r=0, b=0, t=40)
# )

# fig.show()

import pandas as pd
import numpy as np
from sklearn.neighbors import KDTree
import plotly.graph_objects as go

# ============================================================
# 1. LOAD DATA
# ============================================================
df = pd.read_csv("/content/xyz_with_soilmoisture_fixed.csv")

# Rename if columns differ
df.rename(columns={
    "Longitude": "x",
    "Latitude": "y",
    "Elevation (m)": "z"
}, inplace=True)

points_xyz = df[["x", "y", "z"]].values
soil = df["soil_moisture"].values

print("Loaded", len(df), "points")

# ============================================================
# 2. KD-TREE FOR NEIGHBOR SEARCH
# ============================================================
tree = KDTree(points_xyz[:, :2], leaf_size=40)

# Number of neighbors (you can modify)
K = 20

# ============================================================
# 3. PCA-PLANE SLOPE ESTIMATION
# ============================================================
def local_slope_pca(neighbors):
    """
    neighbors : Nx3 array of XYZ coordinates
    returns slope in degrees using PCA plane fitting
    """
    # Mean center
    mean = neighbors.mean(axis=0)
    centered = neighbors - mean

    # PCA (SVD)
    _, _, Vt = np.linalg.svd(centered)

    # Plane normal
    nx, ny, nz = Vt[-1]

    # Slope relative to horizontal
    slope_rad = np.arctan(np.sqrt(nx*2 + ny*2) / np.abs(nz))
    return np.degrees(slope_rad)


# ============================================================
# 4. CALCULATE SLOPE FOR EACH POINT
# ============================================================
slopes = np.zeros(len(points_xyz))

for i in range(len(points_xyz)):
    # Query neighbors
    _, idx = tree.query(points_xyz[i:i+1, :2], k=K)
    neighbors = points_xyz[idx[0]]

    slopes[i] = local_slope_pca(neighbors)

df["slope_deg"] = slopes

print("Slope calculation done!")
print("Slope Range:", slopes.min(), "to", slopes.max())

# ============================================================
# 5. FIND HIGH-SLOPE + HIGH-MOISTURE POINTS
# ============================================================
# ============================================================
# 5. TOP 25% ELEVATION FILTER
# ============================================================
z_75 = df["z"].quantile(0.75)
df["high_elev"] = df["z"] >= z_75

# ============================================================
# 6. HIGH SLOPE + HIGH MOISTURE + HIGH ELEVATION
# ============================================================
SLOPE_THRESHOLD = 28
MOISTURE_THRESHOLD = 0.25

mask = (
    (df["slope_deg"] > SLOPE_THRESHOLD) &
    (df["soil_moisture"] > MOISTURE_THRESHOLD) &
    (df["high_elev"] == True)
)

risk_df = df[mask]

print("Points before limit:", len(risk_df))

# ============================================================
# 7. LIMIT TO TOP 0.4% OF ORIGINAL DATASET
# ============================================================
fraction = 0.004   # 0.4%

# Based on original dataset size, NOT filtered risk_df
top_n = max(1, int(len(df) * fraction))

# But risk_df may have fewer points — so limit safely
top_n = min(top_n, len(risk_df))

risk_df = risk_df.sort_values(by="z", ascending=False).head(top_n)

print(f"Original dataset size: {len(df)}")
print(f"0.4% of original dataset = {int(len(df) * fraction)}")
print(f"Selected (min of above and filtered count): {len(risk_df)}")

risk_df.to_csv("/content/high_slope_high_moisture_top25_z_top0_4_percent.csv", index=False)

print("Saved -> /content/high_slope_high_moisture_top25_z_top0_4_percent.csv")

# ============================================================
# 6. OPTIONAL: 3D PLOT OF HIGH-SLOPE & HIGH-MOISTURE POINTS
# ============================================================
fig = go.Figure()

# Base terrain (small sample for speed)
idx = np.random.choice(len(df), size=5000, replace=False)
fig.add_trace(go.Scatter3d(
    x=df.iloc[idx]["x"],
    y=df.iloc[idx]["y"],
    z=df.iloc[idx]["z"],
    mode='markers',
    marker=dict(size=2, color=df.iloc[idx]["slope_deg"], colorscale="Viridis"),
    name="Terrain"
))

# High-risk landslide candidate points
fig.add_trace(go.Scatter3d(
    x=risk_df["x"],
    y=risk_df["y"],
    z=risk_df["z"],
    mode='markers',
    marker=dict(size=1, color="red"),
    name="High Slope + High Moisture"
))

fig.update_layout(
    title="3D Terrain + High-Risk Points",
    scene=dict(
        xaxis_title='Longitude',
        yaxis_title='Latitude',
        zaxis_title='Elevation',
        aspectratio=dict(x=10, y=1, z=1)
    ),
    height=700
)

fig.show()

import pandas as pd
import numpy as np
from scipy.interpolate import griddata
import plotly.graph_objects as go

# -------------------------------------------------------------
# 1. LOAD ORIGINAL TERRAIN (already in METERS)
# -------------------------------------------------------------
df = pd.read_csv("/content/xyz_with_soilmoisture_fixed.csv")

x = df["x"].values  # already meters
y = df["y"].values  # already meters
z = df["z"].values  # meters

# -------------------------------------------------------------
# 2. LOAD HOLE POINTS (ALSO already in meters)
# -------------------------------------------------------------
df_holes = pd.read_csv("/content/high_slope_high_moisture_top25_z_top0_4_percent.csv")

xh = df_holes["x"].values  # meters
yh = df_holes["y"].values  # meters

# -------------------------------------------------------------
# 3. AUTO GRID RESOLUTION (aspect-aware, data-aware)
# -------------------------------------------------------------
x_range = x.max() - x.min()
y_range = y.max() - y.min()

resolution_per_km = 30
Nx_init = (x_range / 1000) * resolution_per_km
Ny_init = (y_range / 1000) * resolution_per_km

aspect = x_range / max(y_range, 1e-9)
cells_init = Nx_init * Ny_init
max_cells = 4 * len(df)

if cells_init > max_cells:
    cells_target = max_cells
    Ny = int(np.sqrt(cells_target / aspect))
    Nx = int(aspect * Ny)
else:
    Nx = int(Nx_init)
    Ny = int(Ny_init)

Nx = max(Nx, 200)
Ny = max(Ny, 200)

print(f"Grid resolution → Nx={Nx}, Ny={Ny}")

xg = np.linspace(x.min(), x.max(), Nx)
yg = np.linspace(y.min(), y.max(), Ny)
X, Y = np.meshgrid(xg, yg)

# -------------------------------------------------------------
# 4. INTERPOLATE ELEVATION TO REGULAR GRID (FAST LINEAR)
# -------------------------------------------------------------
Z = griddata(
    (x, y),
    z,
    (X, Y),
    method="linear"
)
Z = np.nan_to_num(Z, nan=np.nanmean(z))

# -------------------------------------------------------------
# 4. GLOBAL SETTINGS (bowl physics)
# -------------------------------------------------------------
base_radius = 300      # meters
dr = 50                # random radius variation
base_depth = 1         # meters
dz = 0.5               # random depth variation

# -------------------------------------------------------------
# 5. APPLY RANDOMIZED GAUSSIAN HOLES (SAFE LOOP VERSION)
# -------------------------------------------------------------
total_bowls = np.zeros_like(Z)

for i in range(len(df_holes)):
    hx = xh[i]
    hy = yh[i]

    # Randomized radius and depth
    radius_final = base_radius + np.random.uniform(-dr, dr)
    depth_final  = base_depth  + np.random.uniform(-dz, dz)
    sigma = radius_final / 2

    # Compute bowl effect for this hole
    dx = X - hx
    dy = Y - hy
    R = np.sqrt(dx**2 + dy**2)

    bowl = depth_final * np.exp(-(R**2) / (2 * sigma**2))

    total_bowls -= bowl


# -------------------------------------------------------------
# 6. FINAL TERRAIN
# -------------------------------------------------------------
Z_mod = Z + total_bowls

# -------------------------------------------------------------
# 7. VISUALIZATION
# -------------------------------------------------------------
fig = go.Figure(data=[
    go.Surface(
        x=X,
        y=Y,
        z=Z_mod,
        surfacecolor=total_bowls,
        colorscale="RdBu",
        colorbar=dict(title="dz")
    )
])

fig.update_layout(
    title="Real-Scale Terrain With Gaussian Holes (Optimized)",
    height=900,
    scene=dict(
        aspectmode="manual",
        aspectratio=dict(x=10, y=1, z=1)  # z exaggerated
    )
)

fig.show()

# -------------------------------------------------------------
# 8. SAVE OUTPUT
# -------------------------------------------------------------
df_after = df.copy()

# interpolate modified Z back to original scattered points
points_after = griddata(
    (X.flatten(), Y.flatten()),
    Z_mod.flatten(),
    (x, y),
    method="linear"
)

df_after["z"] = np.nan_to_num(points_after, nan=z)
df_after.to_csv("/content/terrain_after.csv", index=False)
df.to_csv("/content/terrain_before.csv", index=False)

print("Saved:")
print(" - /content/terrain_after.csv")
print(" - /content/terrain_before.csv")

import pandas as pd
import numpy as np
from scipy.interpolate import griddata

# ======================================================================
# 1. LOAD TERRAIN BEFORE AND AFTER
# ======================================================================
df_before = pd.read_csv("/content/terrain_before.csv")
df_after  = pd.read_csv("/content/terrain_after.csv")

x = df_after["x"].values
y = df_after["y"].values
z_after = df_after["z"].values
z_before = df_before["z"].values


# # ======================================================================
# # 2. REBUILD GRID FROM TERRAIN AFTER
# # ======================================================================
# Nx = 400  # horizontal resolution
# Ny = 400  # vertical resolution

# xg = np.linspace(x.min(), x.max(), Nx)
# yg = np.linspace(y.min(), y.max(), Ny)
# X, Y = np.meshgrid(xg, yg)

# # Interpolate AFTER terrain to grid
# Z_after_grid = griddata(
#     (x, y),
#     z_after,
#     (X, Y),
#     method="linear"
# )
# Z_after_grid = np.nan_to_num(Z_after_grid, nan=np.nanmean(z_after))


# # ======================================================================
# # 3. COMPUTE TERRAIN METRICS ON THE GRID
# # ======================================================================
# dx = xg[1] - xg[0]
# dy = yg[1] - yg[0]

# # First derivatives
# Zx, Zy = np.gradient(Z_after_grid, dx, dy)

# # Second derivatives
# Zxx, Zxy = np.gradient(Zx, dx, dy)
# Zyx, Zyy = np.gradient(Zy, dx, dy)

# # ------------------ SLOPE (degrees) ------------------
# slope_rad = np.sqrt(Zx**2 + Zy**2)
# slope_deg = np.degrees(np.arctan(slope_rad))

# # ------------------ ASPECT (0–360) -------------------
# aspect = np.degrees(np.arctan2(-Zx, Zy))
# aspect = (aspect + 360) % 360

# # ------------------ TRI ------------------------------
# shifted = []
# for xs in [-1, 0, 1]:
#     for ys in [-1, 0, 1]:
#         if xs == 0 and ys == 0:
#             continue
#         shifted.append(
#             np.abs(Z_after_grid - np.roll(np.roll(Z_after_grid, xs, axis=0), ys, axis=1))
#         )
# TRI = np.mean(shifted, axis=0)

# # ------------------ CURVATURE COMPONENTS --------------
# p = Zx
# q = Zy
# r = Zxx
# s = Zxy
# t = Zyy

# profile_curvature = (r*p*p + 2*s*p*q + t*q*q) / (p*p + q*q + 1e-12)
# plan_curvature    = (r*q*q - 2*s*p*q + t*p*p) / (
#     (p*p + q*q)*np.sqrt(p*p + q*q + 1e-12) + 1e-12
# )
# curvature = Zxx + Zyy

# # ------------------ TWI -------------------------------
# cell_area = dx * dy
# TWI = np.log(cell_area / (np.tan(np.radians(slope_deg)) + 1e-12))


# # ======================================================================
# # 4. INTERPOLATE METRICS BACK TO ORIGINAL POINTS
# # ======================================================================
# metrics = {
#     "slope_deg": slope_deg,
#     "aspect_deg": aspect,
#     "TRI": TRI,
#     "curvature": curvature,
#     "profile_curvature": profile_curvature,
#     "plan_curvature": plan_curvature,
#     "TWI": TWI,
# }

# for name, grid_metric in metrics.items():
#     interp_vals = griddata(
#         (X.flatten(), Y.flatten()),
#         grid_metric.flatten(),
#         (x, y),
#         method="linear"
#     )
#     df_after[name] = np.nan_to_num(interp_vals, nan=np.nanmean(grid_metric))


# ======================================================================
# 5. COMPUTE dz AS BINARY FLAG
# ======================================================================
dz_raw = df_after["z"] - z_before

# Condition: abs(dz) > 20 → 1 else 0
df_after["dz"] = (np.abs(dz_raw) > 20).astype(int)


# ======================================================================
# 6. SAVE FINAL OUTPUT
# ======================================================================
df_after.to_csv("/content/terrain_after_with_metrics.csv", index=False)

print("Saved:")
print(" - /content/terrain_after_with_metrics.csv")

df[['x','y','z']] = df_after[['x','y','z']].round(1)

# keep only unique combinations
df_unique = df.drop_duplicates(subset=['x','y','z'])

print(df_unique)

df_unique.info()

import os

output_dir = '/content/drive/MyDrive/LandSense/HGT_20_Segments/Point_with_soil_moisture_Ground_Truth_without_segment1'

# Create the directory if it does not exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Construct the full path for the file
output_file_path = os.path.join(output_dir, 'segment_1.csv')

df_unique.to_csv(output_file_path, index=False)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def generate_gaussian_cube(center=(0,0,0), edge=3, n_points=100, mean=0, std=0.5):
    """
    center : actual true point at middle of cube
    edge   : cube edge length in meters (3 m)
    n_points : number of noisy points (100)
    mean   : Gaussian mean
    std    : Gaussian std deviation
    """
    cx, cy, cz = center

    # Radius = half of the cube edge
    r = edge / 2.0   # for 3-meter cube → r = 1.5 m

    # Generate Gaussian noise
    noise_x = np.random.normal(mean, std, n_points)
    noise_y = np.random.normal(mean, std, n_points)
    noise_z = np.random.normal(mean, std, n_points)

    # Clip noise so that points stay inside cube boundaries
    noise_x = np.clip(noise_x, -r, r)
    noise_y = np.clip(noise_y, -r, r)
    noise_z = np.clip(noise_z, -r, r)

    # Create noisy points
    x_points = cx + noise_x
    y_points = cy + noise_y
    z_points = cz + noise_z

    # KDE plot for noise distribution
    plt.figure(figsize=(14,5))
    plt.suptitle("Gaussian Noise KDE for Cube Distribution", fontsize=16)

    plt.subplot(1,3,1)
    sns.kdeplot(noise_x, fill=True, color="blue")
    plt.title("KDE of X-axis Noise")
    plt.xlabel("Noise (meters)")

    plt.subplot(1,3,2)
    sns.kdeplot(noise_y, fill=True, color="green")
    plt.title("KDE of Y-axis Noise")
    plt.xlabel("Noise (meters)")

    plt.subplot(1,3,3)
    sns.kdeplot(noise_z, fill=True, color="red")
    plt.title("KDE of Z-axis Noise")
    plt.xlabel("Noise (meters)")

    plt.tight_layout()
    plt.show()

    return x_points, y_points, z_points

# Generate points inside a 3-meter cube
x, y, z = generate_gaussian_cube(
    center=(0, 0, 0),
    edge=3,
    n_points=100,
    mean=0,
    std=0.5   # adjust for more / less noise
)

import pandas as pd
import numpy as np
from tqdm import tqdm
import random

# ============================
# 1. Load Your Dataset
# ============================
df = pd.read_csv("/content/drive/MyDrive/LandSense/HGT_20_Segments/Point_with_soil_moisture_Ground_Truth_without_segment1")

print("Original dataset size:", len(df))

# ============================
# 2. Downsample RANDOM 15%
# ============================
fraction = 1
df_small = df.sample(frac=fraction, random_state=42).reset_index(drop=True)

print("Downsampled dataset size:", len(df_small))


# =============================================================
# Function to generate Gaussian noise inside 3m cube
# =============================================================
def generate_gaussian_cube(center, edge=15, n_points=100, mean=0, std=0.5):
    cx, cy, cz = center
    r = edge / 2.0  # cube half-edge (1.5 meters)

    # Gaussian noise for 100 samples
    nx = np.random.normal(mean, std, n_points)
    ny = np.random.normal(mean, std, n_points)
    nz = np.random.normal(mean, std, n_points)

    # Clip noise so points stay inside cube
    nx = np.clip(nx, -r, r)
    ny = np.clip(ny, -r, r)
    nz = np.clip(nz, -r, r)

    # Return 100 noisy samples
    return cx + nx, cy + ny, cz + nz


# =============================================================
# 3. Create noisy point for EACH of the downsampled points
# =============================================================
noisy_x = []
noisy_y = []
noisy_z = []

for i in tqdm(range(len(df_small)), desc="Generating noisy data"):
    cx = df_small.loc[i, "x"]
    cy = df_small.loc[i, "y"]
    cz = df_small.loc[i, "z"]

    # Generate 100 noisy samples inside cube
    xs, ys, zs = generate_gaussian_cube(center=(cx, cy, cz))

    # Pick ONE random noisy sample out of 100
    idx = random.randint(0, 99)

    noisy_x.append(xs[idx])
    noisy_y.append(ys[idx])
    noisy_z.append(zs[idx])

# Add noisy coordinates to DataFrame
df_small["x_noisy"] = noisy_x
df_small["y_noisy"] = noisy_y
df_small["z_noisy"] = noisy_z

# Save
df_small.to_csv("/content/noisy_downsampled_dataset.csv", index=False)

print("\nSaved → /content/noisy_downsampled_dataset.csv")

df = pd.read_csv("/content/noisy_downsampled_dataset.csv")
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

# Compute actual noise differences
df["dx"] = df["x_noisy"] - df["x"]
df["dy"] = df["y_noisy"] - df["y"]
df["dz"] = df["z_noisy"] - df["z"]

plt.figure(figsize=(14,5))
plt.suptitle("Gaussian Noise KDE for Cube Distribution (Δ Noise)", fontsize=16)

# ---------------- Δx ----------------
plt.subplot(1,3,1)
sns.kdeplot(df["dx"], fill=True)
plt.title("KDE of ΔX (noise)")
plt.xlabel("ΔX (meters)")

# ---------------- Δy ----------------
plt.subplot(1,3,2)
sns.kdeplot(df["dy"], fill=True)
plt.title("KDE of ΔY (noise)")
plt.xlabel("ΔY (meters)")

# ---------------- Δz ----------------
plt.subplot(1,3,3)
sns.kdeplot(df["dz"], fill=True)
plt.title("KDE of ΔZ (noise)")
plt.xlabel("ΔZ (meters)")

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np

# =============================================================
# 1. LOAD THE FINAL TERRAIN DATA
# =============================================================
df = pd.read_csv("/content/terrain_after_with_metrics.csv")
print("Original points:", len(df))

# =============================================================
# 2. RANDOM DOWNSAMPLING TO 15%
# =============================================================
df_down = df.sample(frac=0.15, random_state=42).reset_index(drop=True)

print("Downsampled points:", len(df_down))

# =============================================================
# 3. ADD CLIPPED GAUSSIAN NOISE (no outliers)
# =============================================================
noise_std = 2.0
clip_limit = 3 * noise_std   # ±6 meters

# Generate clipped noise for each axis
noise_x = np.clip(np.random.normal(0, noise_std, len(df_down)), -clip_limit, clip_limit)
noise_y = np.clip(np.random.normal(0, noise_std, len(df_down)), -clip_limit, clip_limit)
noise_z = np.clip(np.random.normal(0, noise_std, len(df_down)), -clip_limit, clip_limit)

# Apply noise
df_down["x_noisy"] = df_down["x"] + noise_x
df_down["y_noisy"] = df_down["y"] + noise_y
df_down["z_noisy"] = df_down["z"] + noise_z

print(f"Noise added (mean=0, std={noise_std}, clipped to ±{clip_limit} m)")

# =============================================================
# 4. SAVE OUTPUT
# =============================================================
df_down.to_csv("/content/terrain_after_downsampled_noisy.csv", index=False)

print("Saved:")
print(" - /content/terrain_after_downsampled_noisy.csv")

import numpy as np
import pandas as pd
from sklearn.neighbors import KDTree
import plotly.graph_objects as go

# ============================================================
# 1. LOAD FINAL DATASET
# ============================================================
df = pd.read_excel('/content/drive/MyDrive/LandSense/HGT_20_Segments/microsegment_noisy/segment_2_10_noisy.xlsx')

points = df[["x_noisy", "y_noisy", "z_noisy"]].values
print("Loaded points:", points.shape)

# ============================================================
# 2. KD-TREE FOR NEIGHBOR SEARCH
# ============================================================
tree = KDTree(points[:, :2], leaf_size=40)

# ============================================================
# 3. SELECT RECONSTRUCTION CENTERS
# ============================================================
# Use random 10% of points as centers
num_centers = int(0.1 * len(points))
center_idx = np.random.choice(len(points), num_centers, replace=False)
centers = points[center_idx]

# ============================================================
# 4. LOCAL PCA-BASED RECONSTRUCTION
# ============================================================
def reconstruct_patch(center, tree, points,
                      K=40, samples=80, radius=2.0):
    """
    center : (3,)
    returns : (samples, 3)
    """
    _, idx = tree.query(center[:2].reshape(1, -1), k=K)
    neigh = points[idx[0]]

    # PCA
    mean = neigh.mean(axis=0)
    X = neigh - mean
    _, _, Vt = np.linalg.svd(X)
    t1, t2 = Vt[0], Vt[1]

    # Sample on tangent plane
    u = np.random.uniform(-radius, radius, samples)
    v = np.random.uniform(-radius, radius, samples)

    patch = mean + np.outer(u, t1) + np.outer(v, t2)
    return patch


# ============================================================
# 5. RECONSTRUCT ENTIRE PCD
# ============================================================
reconstructed = []

for c in centers:
    patch = reconstruct_patch(
        c, tree, points,
        K=50,
        samples=120,
        radius=100.0
    )
    reconstructed.append(patch)

reconstructed = np.vstack(reconstructed)
print("Reconstructed points:", reconstructed.shape)

# ============================================================
# 6. SAVE RECONSTRUCTED PCD
# ============================================================
df_rec = pd.DataFrame(reconstructed, columns=["x", "y", "z"])
df_rec.to_csv("/content/reconstructed_pcd.csv", index=False)

print("Saved → /content/reconstructed_pcd.csv")

len(df_rec)

# Calculate number of unique tuples (rows)
num_unique = len(df_rec.drop_duplicates())
print(f"Number of unique tuples: {num_unique}")

df_rec.info()

import numpy as np
import pandas as pd
import plotly.graph_objects as go

# ============================================================
# 1. LOAD DATA
# ============================================================
df_noisy = pd.read_excel('/content/drive/MyDrive/LandSense/HGT_20_Segments/microsegment_noisy/segment_2_10_noisy.xlsx')
df_rec   = pd.read_csv("/content/reconstructed_pcd.csv")

points_noisy = df_noisy[["x_noisy", "y_noisy", "z_noisy"]].values
points_rec   = df_rec[["x", "y", "z"]].values

# print("Noisy points:", points_noisy.shape)
# print("Reconstructed points:", points_rec.shape)

# # ============================================================
# # 2. SUBSAMPLING FOR PERFORMANCE
# # ============================================================
# def subsample(points, max_pts):
#     if len(points) > max_pts:
#         idx = np.random.choice(len(points), max_pts, replace=False)
#         return points[idx]
#     return points

# points_noisy = subsample(points_noisy, 6000)
# points_rec   = subsample(points_rec, 9000)

# # ============================================================
# # 3. COMMON NORMALIZATION (IMPORTANT)
# # ============================================================
# # Use SAME normalization for both so scale is identical
# all_points = np.vstack([points_noisy, points_rec])

# mean = all_points.mean(axis=0)
# std  = all_points.std(axis=0) + 1e-9

# def normalize(P):
#     return (P - mean) / std

noisy_vis = points_noisy
rec_vis   = points_rec

# ============================================================
# 4. COMMON LAYOUT SETTINGS
# ============================================================
common_scene = dict(
    aspectmode="manual",
    aspectratio=dict(x=1, y=1, z=0.4),
    xaxis_title="X",
    yaxis_title="Y",
    zaxis_title="Z"
)

# ============================================================
# 5. PLOT 1 — NOISY SPARSE PCD
# ============================================================
fig_noisy = go.Figure()

fig_noisy.add_trace(go.Scatter3d(
    x=noisy_vis[:, 0],
    y=noisy_vis[:, 1],
    z=noisy_vis[:, 2],
    mode='markers',
    marker=dict(
        size=2,
        color='blue',
        opacity=0.9
    ),
    name="Noisy Sparse PCD"
))

fig_noisy.update_layout(
    title="Noisy Sparse PCD (terrain_after_downsampled_noisy.csv)",
    scene=common_scene,
    height=850,
    margin=dict(l=0, r=0, b=0, t=40)
)

fig_noisy.show()

# ============================================================
# 6. PLOT 2 — RECONSTRUCTED DENSE PCD
# ============================================================
fig_rec = go.Figure()

fig_rec.add_trace(go.Scatter3d(
    x=rec_vis[:, 0],
    y=rec_vis[:, 1],
    z=rec_vis[:, 2],
    mode='markers',
    marker=dict(
        size=1,
        color='red',
        opacity=0.9
    ),
    name="Reconstructed Dense PCD"
))

fig_rec.update_layout(
    title="Reconstructed Dense PCD",
    scene=common_scene,
    height=850,
    margin=dict(l=0, r=0, b=0, t=40)
)

fig_rec.show()

import numpy as np
import pandas as pd
import plotly.graph_objects as go

# ============================================================
# 1. LOAD DATA
# ============================================================
df_noisy = pd.read_excel('/content/drive/MyDrive/LandSense/HGT_20_Segments/microsegment_noisy/segment_2_10_noisy.xlsx')
df_rec   = pd.read_csv("/content/reconstructed_pcd.csv")

points_noisy = df_noisy[["x_noisy", "y_noisy", "z_noisy"]].values
points_rec   = df_rec[["x", "y", "z"]].values

print("Noisy points:", points_noisy.shape)
print("Reconstructed points:", points_rec.shape)

# ============================================================
# 2. SUBSAMPLE (IMPORTANT FOR PERFORMANCE)
# ============================================================
def subsample(points, max_pts=8000):
    if len(points) > max_pts:
        idx = np.random.choice(len(points), max_pts, replace=False)
        return points[idx]
    return points

points_noisy_vis = subsample(points_noisy, 5000)
points_rec_vis   = subsample(points_rec, 8000)

# ============================================================
# 3. NORMALIZE FOR VISUALIZATION ONLY
# ============================================================
def normalize_for_vis(P):
    Pn = P.copy()
    mean = Pn.mean(axis=0)
    std  = Pn.std(axis=0) + 1e-9
    return (Pn - mean) / std

noisy_vis = normalize_for_vis(points_noisy_vis)
rec_vis   = normalize_for_vis(points_rec_vis)

# ============================================================
# 4. CREATE PLOT
# ============================================================
fig = go.Figure()

# ---- Noisy Sparse Points ----
fig.add_trace(go.Scatter3d(
    x=noisy_vis[:, 0],
    y=noisy_vis[:, 1],
    z=noisy_vis[:, 2],
    mode='markers',
    marker=dict(
        size=2,
        color='blue',
        opacity=0.5
    ),
    name="Noisy Sparse PCD"
))

# ---- Reconstructed Dense Points ----
fig.add_trace(go.Scatter3d(
    x=rec_vis[:, 0],
    y=rec_vis[:, 1],
    z=rec_vis[:, 2],
    mode='markers',
    marker=dict(
        size=1,
        color='red',
        opacity=0.8
    ),
    name="Reconstructed Dense PCD"
))

# ============================================================
# 5. FIX ASPECT RATIO (CRITICAL)
# ============================================================
fig.update_layout(
    title="PCD Reconstruction from terrain_after_downsampled_noisy.csv",
    scene=dict(
        aspectmode="manual",
        aspectratio=dict(
            x=1,    # horizontal
            y=1,    # horizontal
            z=0.4   # vertical exaggeration
        ),
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Z"
    ),
    height=850,
    margin=dict(l=0, r=0, b=0, t=40)
)

fig.show()



import pandas as pd
import numpy as np
import plotly.graph_objects as go
import os

# ============================================================
# 1. LOAD DATA
# ============================================================
# df = pd.read_csv("/content/drive/MyDrive/LandSense/HGT_20_Segments/Point_with_soil_moisture_Ground_Truth_without_segment1")
df = df_unique
# ============================================================
# 2. TILE SIZE
# ============================================================
tile_size = 1000
x_max = df["x"].max()
num_tiles = int(np.ceil(x_max / tile_size))

print("Total tiles =", num_tiles)

# ============================================================
# 3. OUTPUT DIRECTORY
# ============================================================
output_dir = "/content/drive/MyDrive/LandSense/HGT_20_Segments/micromicrosegmentuni/"
os.makedirs(output_dir, exist_ok=True)

tile_info = []

# ============================================================
# 4. LOOP THROUGH TILES
# ============================================================
for t in range(num_tiles):

    x_start = t * tile_size
    x_end   = (t + 1) * tile_size

    tile_df = df[(df["x"] >= x_start) & (df["x"] < x_end)]

    if len(tile_df) == 0:
        continue

    # ---- Relief (for info only) ----
    zmin = tile_df["z"].min()
    zmax = tile_df["z"].max()
    relief = zmax - zmin

    tile_info.append([t+1, x_start, x_end, zmin, zmax, relief])

    # ---- Save ALL tiles ----
    tile_filename = f"segment_{t+1}.xlsx"
    tile_path = os.path.join(output_dir, tile_filename)
    tile_df.to_excel(tile_path, index=False)

    print(f"[SAVED] Tile {t+1} | Points: {len(tile_df)}")

    # ============================================================
    # PURE SCATTER VISUALIZATION
    # ============================================================

    fig = go.Figure()

    fig.add_trace(go.Scatter3d(
        x=tile_df["x"],
        y=tile_df["y"],
        z=tile_df["z"],
        mode='markers',
        marker=dict(
            size=3,
            color=tile_df["z"],
            colorscale="Viridis",
            opacity=0.85
        )
    ))

    fig.update_layout(
        title=f"Tile {t+1}/{num_tiles} | Relief = {relief:.1f} m",
        scene=dict(
            xaxis_title='X',
            yaxis_title='Y',
            zaxis_title='Elevation',
            aspectratio=dict(x=1, y=1, z=0.5)
        ),
        height=700
    )

    fig.show()

# ============================================================
# 5. EXPORT SUMMARY
# ============================================================
summary_df = pd.DataFrame(tile_info, columns=[
    "tile_id", "x_start", "x_end", "zmin", "zmax", "relief"
])

summary_path = os.path.join(output_dir, "tile_summary.xlsx")
summary_df.to_excel(summary_path, index=False)

print("\nSaved summary:", summary_path)

df_after.info()

import os
import pandas as pd
import numpy as np
from tqdm import tqdm
import random

# ======================================================
# Paths
# ======================================================
input_dir = "/content/drive/MyDrive/LandSense/HGT_20_Segments/micromicrosegmentuni"
output_dir = "/content/drive/MyDrive/LandSense/HGT_20_Segments/micromicrosegmentuni_noisy"

os.makedirs(output_dir, exist_ok=True)

# ======================================================
# Noise generation function (same as yours)
# ======================================================
def generate_gaussian_cube(center, edge=3, n_points=100, mean=0, std=0.5):
    cx, cy, cz = center
    r = edge / 2.0  # 1.5 m

    nx = np.random.normal(mean, std, n_points)
    ny = np.random.normal(mean, std, n_points)
    nz = np.random.normal(mean, std, n_points)

    nx = np.clip(nx, -r, r)
    ny = np.clip(ny, -r, r)
    nz = np.clip(nz, -r, r)

    return cx + nx, cy + ny, cz + nz

# ======================================================
# Process ALL Excel files
# ======================================================
files = sorted([f for f in os.listdir(input_dir) if f.endswith(".xlsx")])

print("Total files found:", len(files))

for file in files:
    print(f"\nProcessing → {file}")

    # ---------------------------
    # Load file
    # ---------------------------
    file_path = os.path.join(input_dir, file)
    df = pd.read_excel(file_path)

    print("Original size:", len(df))

    # ---------------------------
    # Downsample 15%
    # ---------------------------
    df_small = df.sample(frac=0.20, random_state=42).reset_index(drop=True)
    print("Downsampled size:", len(df_small))

    # ---------------------------
    # Generate noisy point
    # ---------------------------
    noisy_x, noisy_y, noisy_z = [], [], []

    for i in tqdm(range(len(df_small)), desc="Adding noise"):
        cx = df_small.loc[i, "x"]
        cy = df_small.loc[i, "y"]
        cz = df_small.loc[i, "z"]

        xs, ys, zs = generate_gaussian_cube(center=(cx, cy, cz))
        idx = random.randint(0, 99)

        noisy_x.append(xs[idx])
        noisy_y.append(ys[idx])
        noisy_z.append(zs[idx])

    df_small["x_noisy"] = noisy_x
    df_small["y_noisy"] = noisy_y
    df_small["z_noisy"] = noisy_z

    # ---------------------------
    # Save output
    # ---------------------------
    output_file = file.replace(".xlsx", "_noisy.xlsx")
    output_path = os.path.join(output_dir, output_file)

    df_small.to_excel(output_path, index=False)

    print("Saved →", output_path)

print("\n✅ All 43 files processed successfully.")

path = "/content/drive/MyDrive/LandSense/HGT_20_Segments/micromicrosegmentuni/segment_100.xlsx"

# Read Excel
df = pd.read_excel(path)

# Min and Max of x, y, z
result = df[['x','y','z']].agg(['min','max'])
print(result)

# ============================================================
# ONE-SAMPLE VISUALIZATION
# Noisy XLSX vs Ground Truth (Scatter Only)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


# -----------------------------
# 1. PATHS
# -----------------------------
gt_xlsx = "/content/drive/MyDrive/LandSense/HGT_20_Segments/micromicrosegment/segment_2_9.xlsx"
noisy_xlsx = "/content/noisy_downsampled_dataset.csv"


# -----------------------------
# 2. LOAD POINT CLOUD FROM XLSX
# -----------------------------
def load_pc_xlsx(path):
    df = pd.read_csv(path)
    numeric_cols = df.select_dtypes(include=[np.number]).columns[:3]
    return df[numeric_cols].values.astype(np.float32)


# gt_pc = load_pc_xlsx(gt_xlsx)
noisy_pc = load_pc_xlsx(noisy_xlsx)


# -----------------------------
# 3. DOWNSAMPLE FOR VISUALIZATION
# -----------------------------
def downsample(pc, max_points=4000):
    if pc.shape[0] <= max_points:
        return pc
    idx = np.random.choice(pc.shape[0], max_points, replace=False)
    return pc[idx]


gt_pc = downsample(gt_pc)
noisy_pc = downsample(noisy_pc)


# -----------------------------
# 4. PLOTTING
# -----------------------------
def plot_pc(ax, pc, title, color):
    ax.scatter(pc[:, 0], pc[:, 1], pc[:, 2],
               s=1, c=color, alpha=0.85)
    ax.set_title(title)
    ax.set_axis_off()
    ax.view_init(elev=20, azim=45)


fig = plt.figure(figsize=(12, 6))

ax1 = fig.add_subplot(121, projection="3d")
plot_pc(ax1, noisy_pc, "Noisy Input", "red")

ax2 = fig.add_subplot(122, projection="3d")
plot_pc(ax2, gt_pc, "Ground Truth", "green")

plt.tight_layout()
plt.show()

df = pd.read_excel('/content/drive/MyDrive/LandSense/HGT_20_Segments/microsegment/segment_2_1.xlsx')

df.info()

df.info()

